optionのvalueの型をnumberからTにする
Wizleap-Inc/wiz-ui pull request #1213
Opened 2024-02-18 14:56 UTC by okakyo

# タスク

resolve: #1190 

## 行ったこと
- Option の Value 型を後で注入するように修正
- デフォルトで number になるように修正

2024-02-19 01:13 UTC, ichi-h reviewed
いくつかコメントいたしましたが、大まかな方向はこちらで問題ないと思います！
後はvueやreactのコンポーネントで型引数を受け付けてあげればうまくいきそうな感じがします！
引き続きよろしくお願いいたします！ 🙏

2024-02-19 01:13 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/inputs/search-input/types.ts
>    label: string;
型引数の初期値numberはできればなくしたいなという気持ちがあります！
numberが初期値で指定されていると、「とりあえずnumberを突っ込んでおくか」というコードを生み出しそうな予感がしておりまして、、、 💦 

valueがnumber型になっているものをoptionsに突っ込んだときに、型が自動的に `SearchInputOption<number>` へと切り替わったり、string型のoptionsを突っ込んだときに `SearchInputOption<string>` となっていればOKなので、要は型引数の初期値を気にすることはないのかなと考えています！

ただ、初期値にnumberを入れないと破壊的変更になってしまうといった問題があれば、一旦はこれでも良いかなと考えております！

2024-02-19 01:13 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
>  };
ここのunknownはPropsの型引数で置き換えられると思います！

2024-02-19 01:13 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/inputs/selectbox/components/selectbox.tsx
> +  options: SelectBoxOption<T>[];
ジェネリクスでnullableを許容するというよりは、valueやonChangeのnullableを許容するところに絞って適用するのが良いかなと思います！
（型引数の初期値を使わないのが一番良さそうですが！）

2024-02-27 02:05 UTC, ichi-h requested changes
まず、型にunknownを使うのは避けましょう！
コンポーネントを利用したときにonChange等の型でunknownがでてきてしまうので、これだとコンポーネント自体が使い物にならなくなってしまいます……！

generics componentにしてあげればunknownはなくなり、すべて「T」で置き換えられるはずです！
以下の記事や「generics component」でググれば色々と記事があるので、参考にしてみてください！

- https://ja.vuejs.org/api/sfc-script-setup#generics
- https://qiita.com/flu_bit/items/a319bc9af5a57e0504ef

これを踏まえたうえでもう一回修正をお願いできればと思います！ 🙇

2024-03-02 06:37 UTC, okakyo commented
@ichi-h 

１点確認なのですが、先ほど型定義で提案していただいた `generic="T"` なのですが、調べてみたら Vue 3.3 以降で使用できるものでした。このリポジトリは現在 v3.2 でバージョンを更新しないと使用できないとのことでした。

Vue のバージョンをあげて対応するようにするか、generic を使用しない方針にしたほうがいいと考えているのですが、どちらで対応したほうがいいでしょうか。ご確認のほどよろしくお願いします！

2024-03-02 08:22 UTC, ichi-h commented
@okakyo 
なんと、、、、！？
vue 3.4を使っていると思っていました、、、 :bow:

それであれば上げましょう！
もし上げてみて他コンポーネントに影響ありそうでしたらそのときに考えますか、、、！

2024-03-10 09:38 UTC, okakyo commented
色々試行錯誤してみたのですが、Vue の generics が Props, Emits に 型を適用できたが、ref, methods などへ型を引き継ぐことはできなさそうでした。この解決方法について資料を調べてみたのですが、解決策が見つからないので解決策が見つかるまで一旦保留させてください。

2024-03-12 06:56 UTC, ichi-h commented
@okakyo 
reactの方だけって可能でしょうか……？
vueのところだけ分離して別タスクでやるというのもありかなと考えておりまして……！

2024-03-28 06:22 UTC, ichi-h reviewed
ありがとうございます！ 🙏 🙏 🙏 
何点かコメントがあったので、ご確認のほどよろしくお願いいたします！ 🙇 
（まだ動作確認まで見れていないので改めて行います 🙇 ）

2024-03-28 06:22 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/inputs/search-selector/components/search-selector.tsx
>      return shouldShowAddButton
-1となっているのはaddableが有効になっているときに表示されるボタンだと思うのですが、そのボタンに当てられるvalueは使うことのない値なので、適当に0とかの値を割り当てて、型アサーションを使ってTで型を上書きしてしまってもよいかなぁと思っています、、、笑（もちろんコメントアウトは残す前提）

search-selectorもジェネリクス化が望まれているコンポーネントなので、ここもnumber以外に対応できるとめちゃくちゃありがたいです……！ 🙇  🙇  🙇

2024-03-28 06:22 UTC, ichi-h commented on packages/wiz-ui-react/src/components/custom/chat/components/chat-card.tsx
>                  />
ここの型アサーションは回避できそうでして、例えば、

```suggestion
                <WizSelectBox<T>
                  options={statusOptions}
                  value={status}
                  onChange={(selectedValue) => onChangeStatus?.(selectedValue)}
                  placeholder={statusPlaceholder}
                  expand
                />
```

として、こうするとstatusOptionsの型エラーが出るので、今度はPropsのstatusOptionsを、

```ts
type Props<T> = BaseProps & {
  // 中略
  statusOptions?: ComponentProps<typeof WizSelectBox<T>>["options"];
  // 中略
};
```

とすれば、型アサーションなしで実装できると思います！

2024-08-26 01:12 UTC, closed without merging