Feat/1222 search input 2
Wizleap-Inc/wiz-ui pull request #1273
Opened 2024-04-05 06:11 UTC by okakyo

# タスク

resolve: #1222

- Select Input の実装続き

2024-04-15 06:39 UTC, ichi-h reviewed
slackにて動作確認の動画を投稿しておりますので、そちらからご確認をお願いいたします！ 🙇

2024-05-14 10:48 UTC, RyushiAok requested changes
- 複数選択（`singleSelect=false`）かつタグ表示が有効（`showSelectedItem=true`）のときの動作が定義されていないようです．この場合，アイテム選択後にDropdownを閉じると，選択を全て解除するまでDropdownを開くことができません．
- react版では虫眼鏡アイコンがタグに被ってしまっています
![image](https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/5a777a56-55e1-418b-9128-b25529513697)

2024-05-14 10:56 UTC, RyushiAok commented on packages/wiz-ui-next/src/components/base/inputs/search-input/search-input.vue
> +                @keydown="(e) => onBackspace(item, e)"
`パラメーター 'e' の型は暗黙的に 'any' になります。`という警告を抑制するために型注釈が必要かもしれません
```suggestion
-               @keydown="(e) => onBackspace(item, e)"
+               @keydown="(e: KeyboardEvent) => onBackspace(item, e)"               
```

2024-05-31 00:53 UTC, shuheitachikawa reviewed
1点質問コメントしましたm()m

2024-05-31 00:53 UTC, shuheitachikawa commented on packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
> +                    {value}
[ask] 表示するのはoptionのlabelでなく、valueで問題ないですかね、？

2024-05-31 09:23 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/inputs/search-input/components/search-input.tsx
> +                    {value}
[b36e18d](https://github.com/Wizleap-Inc/wiz-ui/pull/1273/commits/b36e18d2b74626ad54530f47e49e0e4e2a39422b)にて修正いたしました！

2024-06-03 04:56 UTC, ichi-h approved these changes
@RyushiAok 
問題はあるのですが、とりあえずプロダクト側で使えることを優先に動きたいので、一旦これでapprove出します！
問題点は別issueで対応しましょう！
ありがとうございます！

---

# showSelectedItemがtrueのときに、選択したオプションがinput内に表示されるとiconが消える

選択前
<img width="268" alt="スクリーンショット 2024-06-03 10 56 32" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/15f2f148-b7de-4c5b-a348-21bcc14683fb">

選択後

<img width="358" alt="スクリーンショット 2024-06-03 10 56 43" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/cafca310-c817-4fab-82cc-08c795783c65">

期待する挙動

optionを選択してもiconが消えない

# (vue) 長いラベルのoptionを選択すると、アイテムの大きさがinputを貫通する

<img width="408" alt="スクリーンショット 2024-06-03 13 31 24" src="https://github.com/Wizleap-Inc/wiz-ui/assets/85932406/5aec71d0-7b3b-4e11-9d7c-e67cfea69437">

期待する挙動

optionのラベルが長い場合、inputの大きさに合わせてアイテム中の文章が省略される（reactは正しく動いています！）

2024-06-03 05:03 UTC, merged