Feat/timeline-item-header-content
Wizleap-Inc/wiz-ui pull request #1393
Opened 2024-10-27 18:45 UTC by RyushiAok

# タスク

resolve: #1389

2024-10-28 00:12 UTC, ichi-h reviewed
# annotationの位置

annotationはtitleと

![image](https://github.com/user-attachments/assets/fc828404-916d-4caa-85cc-1afc371c84ed)

![image](https://github.com/user-attachments/assets/cebbd3ee-3d38-4776-9eae-4c57c31fede9)

2024-11-21 01:33 UTC, ichi-h requested changes
@RyushiAok 
これ直ってないです、、、、！！
「titleの横」ではなく、「表示する高さを、titleとheaderの縦方向の真ん中」にして欲しいのです、、、、
![image](https://github.com/user-attachments/assets/524fe5c4-12f9-431f-bc8d-e701873fc67c)

2025-01-10 01:00 UTC, ichi-h reviewed
# react: タイトルが横に長いときにannotationが下に回り込む

![image](https://github.com/user-attachments/assets/9d58c3c0-f862-4268-9f2a-767ba310eb80)

2025-04-02 07:52 UTC, RyushiAok commented
![image](https://github.com/user-attachments/assets/d3269480-70b4-40dc-9d70-dcc6df6a2762)
[a124a42](https://github.com/Wizleap-Inc/wiz-ui/pull/1393/commits/a124a420f70df8ec483c7def8d40cbe78e4f20ac) にてしゅうせいいたしました。

2025-04-06 23:12 UTC, ichi-h approved these changes
ありがとうございます！ 🙏

2025-04-06 23:42 UTC, merged