Feat(icon): image, play_circle, pause_circle
Wizleap-Inc/wiz-ui pull request #1405
Opened 2024-11-20 05:51 UTC by RyushiAok

# タスク

resolve: #1399

2024-11-21 01:25 UTC, ichi-h approved these changes
ありがとうございます！ 🙇

2024-11-21 01:27 UTC, ichi-h requested changes
@RyushiAok 
いや、アイコンのデザインの設定が多分違います！
こっちで入れたいです！
<img width="897" alt="スクリーンショット 2024-11-21 10 27 18" src="https://github.com/user-attachments/assets/3ca27761-3adf-4e6c-8250-d4ba8263acca">

2024-11-24 16:43 UTC, RyushiAok commented
修正いたしました！🙏

2024-12-02 00:54 UTC, ichi-h requested changes
@RyushiAok 
keepが変わっていないです、、、、！！！！
<img width="289" alt="スクリーンショット 2024-12-02 9 53 55" src="https://github.com/user-attachments/assets/65fe8c30-cdae-466f-934a-d3110580541e">

2025-01-09 09:12 UTC, RyushiAok commented
memo:

#1399: Bold指定
> image: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:image:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=image&icon.size=24&icon.color=%23e8eaed
> 
> playCircle: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:play_circle:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed
> 
> pauseCircle: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:pause_circle:FILL@0;wght@400;GRAD@0;opsz@24&icon.size=24&icon.color=%23e8eaed

#1409: Filld指定
> https://fonts.google.com/icons?selected=Material+Symbols+Outlined:error:FILL@1;wght@400;GRAD@0;opsz@24&icon.query=error&icon.size=24&icon.color=%23e8eaed

Keep Filled指定
https://github.com/Wizleap-Inc/wiz-ui/pull/1405#pullrequestreview-2471564579

2025-01-10 01:07 UTC, ichi-h approved these changes
ありがとうございます！ 🙇

2025-01-10 01:07 UTC, merged