Feat/datepicker multiple
Wizleap-Inc/wiz-ui pull request #202
Opened 2022-12-18 09:05 UTC by okakyo

# タスク

resolve: #105

2022-12-28 02:55 UTC, sor4chi commented on packages/wiz-ui/src/components/base/calendar/calendar.stories.ts
> +    const defaultValue = new Date(2023, 0, 8, 0, 0, 0, 0);
単純な質問なんですけど、固定日付変えた理由ってなんかありますか？

2022-12-28 03:00 UTC, okakyo commented on packages/wiz-ui/src/components/base/calendar/calendar.stories.ts
> +    const defaultValue = new Date(2023, 0, 8, 0, 0, 0, 0);
このPRで、Date を固定したものに修正したのですが、すでに修正されていてコンフリクトが発生していました。

その際、どちらの書き方で統一するかを考えた際、このPRでは、期限がある場合の例を追加していたためそれに合わせるために修正しました。

2022-12-28 03:21 UTC, sor4chi requested changes
使う側視点で入力・出力の伝播形態に少し手を加えたいなと思っております。
ちょっと設計すり合わせで詰まりそうなので、次回出勤時にhaddleできたらと思います。

2022-12-28 03:21 UTC, sor4chi commented on packages/wiz-ui/src/components/base/calendar/calendar.vue
> +  value: Date | string;
入力型はDate固定にしたいです、DatePickerなども今props.valueがDate型になっていて、幅広い使い方をできないようにしたいのでなんでも一度new Dateして用途を厳しく制限したいという理由です、

2022-12-28 03:21 UTC, sor4chi commented on packages/wiz-ui/src/components/base/inputs/selectbox/selectbox.vue
> +  height: "2.5rem",
height追加してる理由はなんでしょうか？あんまりheight触りたいくないので（デザイン崩れの原因になりやすい）ほかのアプローチがあればそっちに変えたいと思ってます。

2022-12-28 03:21 UTC, sor4chi commented on packages/wiz-ui/src/components/base/inputs/datepicker/multiple-date-picker.vue
> +  (e: "input", value: string): void;
PropsがDate型になればEmitもDate型に統一できて、
```ts
  emits(
    "input",
    `${
      startPeriodData.value.getMonth() + 1
    }/${startPeriodData.value.getDate()}-${
      endPeriodData.value.getMonth() + 1
    }/${endPeriodData.value.getDate()}${setSelectValue}`
  );
```
こういう整形処理も必要ないのではと思います。

2023-03-21 02:06 UTC, ichi-h commented
こちらクローズいたします:bow:

2023-03-21 02:06 UTC, closed without merging