Feat/wiz upload
Wizleap-Inc/wiz-ui pull request #205
Opened 2022-12-20 16:10 UTC by ktanizaw

# タスク

resolve: #174

2022-12-28 04:33 UTC, sor4chi requested changes
数点お願いいたします、わからなかったらhaddleお願いします

2022-12-28 04:33 UTC, sor4chi commented on packages/styles/bases/upload-display.css.ts
> +  width: "504px",
widthの具体値がきになります、ここは100%で大丈夫そうです

2022-12-28 04:33 UTC, sor4chi commented on packages/styles/bases/upload.css.ts
> +const UPLOAD_PADDING_X = "94px";
widthを100%にしてlabelを中央寄せにすればPaddingXいらなくできそうです

2022-12-28 04:33 UTC, sor4chi commented on packages/styles/bases/upload-display.css.ts
> +  borderColor: THEME.color.gray[400],
cursor: pointerにしてUploadのclickableをわかりやすくしていただけると助かります。

2022-12-28 04:33 UTC, sor4chi commented on packages/wiz-ui/src/components/base/inputs/upload/upload.vue
> +        type="file"
inputにmultipleをつけて複数ファイルを選択できるようにして欲しいです

2022-12-28 14:03 UTC, ktanizaw commented on packages/styles/bases/upload-display.css.ts
> +  width: "504px",
100%にするとpadding分が飛び出してしまうのでwidth指定を無くしました。
loadingbarの長さに合わせてちょうど広がるようになりました。

2022-12-28 14:04 UTC, ktanizaw commented on packages/styles/bases/upload.css.ts
> +const UPLOAD_PADDING_X = "94px";
修正しました！

2022-12-28 14:04 UTC, ktanizaw commented on packages/styles/bases/upload-display.css.ts
> +  borderColor: THEME.color.gray[400],
修正しました！

2022-12-28 14:04 UTC, ktanizaw commented on packages/wiz-ui/src/components/base/inputs/upload/upload.vue
> +        type="file"
修正しました！

2022-12-28 15:39 UTC, sor4chi commented
@ktanizaw 
すいません、StorybookにDocsを描けるようになったので追加して欲しいです。
書き方はWizAnchorのSBを参考にしてください。

2023-01-12 04:01 UTC, sor4chi requested changes
WizUI-Nextの方も作っていただけますでしょうか

2023-01-13 08:50 UTC, merged