Feature: WizMenuItem
Wizleap-Inc/wiz-ui pull request #215
Opened 2022-12-28 15:09 UTC by okakyo

# タスク

https://wizleap.slack.com/archives/C02VDE55431/p1672199976456799?thread_ts=1672196603.382819&cid=C02VDE55431 であげられたコンポーネントの実装

- Hover, Active, Disabled を追加
- click 機能の追加

2022-12-28 15:47 UTC, sor4chi commented
@okakyo 
RC出すほどでもないので一点だけ、
Bundle Analyzerのciがdiff 0になっているのでおそらくexportをし忘れてそうです。修正お願いします

2022-12-28 15:47 UTC, sor4chi commented
あ、あとstorybook docsが書けるようになっているのでWizAnchorのSBを参考にしてDocsを記述していただけると助かります！

2022-12-30 00:01 UTC, okakyo commented
以下の２点で修正しました。
- Storybook の記事追加：[81b0039](https://github.com/Wizleap-Inc/wiz-ui/pull/215/commits/81b00391ecd5936f035bd2a62ff757fd1dc2e86e)
- `export` の追加：https://github.com/Wizleap-Inc/wiz-ui/compare/007eebd7e8cabc579230078d07ffe3530d49844d..bf58eb4768fbb78973118ed8b8a5704d2c14ba64

2022-12-30 04:46 UTC, sor4chi requested changes
すいません気づいたことが一点あったので修正お願いします、

2022-12-30 04:46 UTC, sor4chi commented on packages/styles/bases/menu.css.ts
> +});
cssを静的に吐いている仕様上ビルドするとスタイルの適応順序が:classの配列要素順通りには行きません。そのため、同class内に同じcss propertyがあるとスタイルをoverrideできずおそらく今回もcolorが重複しているので本番ビルドするとスタイルのオーバーライドが効かなくて色が変わらないのではないかなと思います。

この場合は
```typescript
export const menuItemStyle = style({
  padding: `${THEME.spacing.xs} ${THEME.spacing.md}`,
});

export const menuItemVariantStyle = styleVariant({
  default: {
    color: THEME.color.gray[600],
    cursor: "pointer",
  },
  hover: {
    color: THEME.color.green[800],
    cursor: "pointer",
  },
  active: {
    color: THEME.color.green[800],
    backgroundColor: THEME.color.white[800],
    fontWeight: 700,
    cursor: "pointer",
  },
  disabled: {
    color: THEME.color.gray[500],
    cursor: "not-allowed",
  }
});
```

このようにかぶるプロパティはすべてVariantaに逃がすことで対応できます。

2022-12-31 08:52 UTC, okakyo commented on packages/styles/bases/menu.css.ts
> +});
[7dfb90b](https://github.com/Wizleap-Inc/wiz-ui/pull/215/commits/7dfb90bfa0f784e6104b0b65c7682fc71bbd7954) にて対応しました。

2023-01-04 03:14 UTC, sor4chi approved these changes
諸々の対応ありがとうございました、LGTMです

2023-01-04 03:14 UTC, merged