tooltipStyleのmax-contentを削除
Wizleap-Inc/wiz-ui pull request #355
Opened 2023-02-07 08:18 UTC by Maple0922

2023-02-17 11:57 UTC, sor4chi requested changes
これ検証したんですが、横幅が十分にある時、max-contentがないとtooltipがのびた幅の中央（つまり変な位置）に表示されてしまいます。
多分Storybookでもその現象が確認できるはずなので、それが解決できないとMergeできないです...

2023-02-22 07:42 UTC, sor4chi approved these changes
oke

2023-02-22 07:43 UTC, sor4chi commented
@Maple0922 ありがとうございました、merge遅くなってしまってすみません

2023-02-22 07:56 UTC, merged

2023-02-23 07:16 UTC, Maple0922 commented
ありがとうございました！！