[Feat]: WizNavItem に disabled 属性と tooltip 機能を追加
Wizleap-Inc/wiz-ui pull request #439
Opened 2023-03-07 13:23 UTC by okakyo

# タスク

resolve: #411

2023-03-09 13:42 UTC, ichi-h reviewed
close時にtooltipは有効にするのかは確認してきます！

---

下の動画では一番上のitemにtooltipをつけたのですが、かぶさってるのか上にあがってこないのが気になりました！

https://user-images.githubusercontent.com/85932406/224039180-7b1f3e1d-1699-4f2f-8592-627be0c10ab0.mp4

2023-03-09 13:42 UTC, ichi-h commented on packages/styles/bases/navigation.css.ts
> +});
disableのときにcursorをnow-allowedにしたいですね！

2023-03-10 07:31 UTC, sor4chi requested changes
storybook上でtooltipが出ている状態（hover状態）でVisual Regression Testをかけたいので、hover状態をmockしてWizTooltipにhoverを渡してください。
やり方はWizTooltipとそのSBを見るとhover等のインタラクションのmock方法がわかると思います

2023-03-14 07:01 UTC, ichi-h approved these changes
自分からは大丈夫です！
そらちーくんの方をお願いいたします:pray:

2023-03-14 10:19 UTC, sor4chi approved these changes

2023-03-14 10:20 UTC, okakyo commented
レビューありがとうございます！
確認ですが、コチラのマージは一旦待ったほうがいいでしょうか。

2023-03-15 05:53 UTC, merged