Feat/popup button group
Wizleap-Inc/wiz-ui pull request #441
Opened 2023-03-08 05:29 UTC by RyushiAok

# タスク

resolve:  #428

2023-03-09 14:23 UTC, ichi-h reviewed
めっちゃ多いですが何卒よろしくお願いいたします…… 🙇 

---

- ホバー時にマージンがまったくないのが気になりました
- ホバーの挙動はselect-boxを参考にしていただければと思います

![スクリーンショット 2023-03-09 22 48 35](https://user-images.githubusercontent.com/85932406/224045045-a572de9e-baf3-4a3b-b13b-0e91cefa75e0.png)

- インデントができたときに、左側にホバーのスタイルが伸びなくてもいいのかは確認する必要がありそうです

![スクリーンショット 2023-03-09 22 49 45](https://user-images.githubusercontent.com/85932406/224045471-04194fb0-a669-4263-850b-77f2bf89ad91.png)

- 設計を見る限り、dividerがどちらかというと下線表示機能のように見えました
- 今の設計の場合、画像のように任意の場所に対して「区切り」を入れるということができないと思うので、ここは改修する必要がありそうです
- また、dividerがgroupの幅に依存するのかは確認事項になりますね

![スクリーンショット 2023-03-09 22 54 40](https://user-images.githubusercontent.com/85932406/224046918-456469a2-ad77-4e93-ad6e-3aea9e5f75d0.png)

- タイトルが文字選択できてしまったのですが、こちらはこれで問題ありませんか？

![スクリーンショット 2023-03-09 22 59 06](https://user-images.githubusercontent.com/85932406/224047870-b874069a-96b1-4966-8b87-39ddcc1d90a1.png)

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.stories.ts
> +      },
clickイベントはstorybookのclick actionを使えませんか？（ボタン系のstoryを見れば何をしたいのかがわかると思います）

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.stories.ts
> +  components: { WizPopupButtonGroup, WizHStack, WizPopupContainer, WizPopup },
popupのstoryが、別画面に遷移したときにも一生表示されているので、popupの開閉の仕組みがほしいですね……

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +import { WizPopupButtonGroup } from ".";
コンポーネントの呼び出しは `@/components` で統一したいですね！

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +});
1文字の変数はインデックスとかの決まりきった命名か、よっぽど狭い範囲以外では使いたくないですね……読めばわかるコードではあるんですが、ちゃんと集中してコードを読まないとそれが何であるかを読み取らないといけないので、ぱっと見で何をしたいのかの判断がつきにくいですね……

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +
どうでもいいところではあるのですが、ちょっと気になったので
undefinedはjsにおいて「未定義」を意味するので、nullとはちょっと扱いが異なるんですよね
慣習として、jsではundefinedを代入するといった、意図的にundefinedを使うということはなくて、「空」の状態を表す場合はnullを使うのが一般的になります

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +  const d: ItemElement = { kind: "divider" };
computedはジェネリクスで型を受け付けてくれるので、ComputedRefという型を明示的に書く必要はないですね！

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +
これは何をするために型になりますか？？（質問です）

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +          "
テンプレート側にここまでロジックが入るなら切り出したさはありますね……

2023-03-09 14:23 UTC, ichi-h commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +      <hr
このv-forに対してkeyがなさそうに見えるのですが大丈夫ですか？？

2023-03-09 14:23 UTC, ichi-h commented on packages/styles/bases/popup-button-group.css.ts
> +  height: THEME.spacing.xl3,
ここにrelative貼っていますが、どこにもabsoluteがないので、不要なのでは？と思いました！

2023-03-10 07:12 UTC, sor4chi commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.stories.ts
> +  for (let i = 1; i <= count; i++) {
（参考程度に）
自分だったらこうします
```ts
const count = 10;

Array(count).fill(0).forEach((_, i) => {
  console.log(i);
})
```

```txt
0
1
2
3
4
5
6
7
8
9
```

2023-03-10 07:19 UTC, sor4chi requested changes
変更お願いします。

@ichi-h 
dividerの責務って要素を区切りたい、ではなくgroupごとに区切りたいだと思うんで、showDividerのやってることがなんか違う感じするんですが僕だけですかね？

2023-03-10 07:19 UTC, sor4chi commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.vue
> +            () => {
handler系処理が副行になるのであれば関数作って切って欲しいです。

2023-03-10 14:11 UTC, RyushiAok commented on packages/styles/bases/popup-button-group.css.ts
> +  height: THEME.spacing.xl3,
そもそもselectBoxStyle使ってませんでした......
削除します！

2023-03-10 15:32 UTC, RyushiAok commented on packages/wiz-ui/src/components/base/popup-button-group/types.ts
> +  | { kind: "group"; title: string; items: Item[]; showDivider?: boolean };
ButtonGroupItemで大丈夫ですかね？

2023-03-10 15:38 UTC, RyushiAok commented on packages/wiz-ui/src/components/base/popup-button-group/types.ts
> +  iconDefaultColor?: "green.800" | "gray.500";
対応しました

2023-03-10 15:38 UTC, RyushiAok commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +import { WizPopupButtonGroup } from ".";
対応しました！

2023-03-10 15:39 UTC, RyushiAok commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +
こちらも対応しました！

2023-03-10 16:28 UTC, RyushiAok commented on packages/wiz-ui/src/components/base/popup-button-group/popup-button-group.vue
> +
コンポーネントが受け取るデータ（ButtonGroupItem[]）と，描画する要素（ItemElement[]）を別で持つことによって，WizPopupButtonGroupに柔軟性を持たせました．

本コンポーネントは，ButtonGroupItem[]を受け取ると，木構造ItemElement[]を生成し，再帰的にレンダリングするという仕組みになっています．この木構造を生成する過程で，デザインの仕様に合わせてdividerを挿入したりしているわけです．そのため，例えば「ボタン単位で区切り線を表示する」といった仕様変更にも容易に対応可能になっています．

現状ではグループごとにdividerを表示するかを制御するだけでよく(true/false)，このコンポーネント使用者側が，dividerの表示位置を制御をする必要はないので，「表示したいデータ（単純，コンポーネントに渡す木構造）」と「レンダリングする要素（複雑，再帰的に描画する木構造）」を分離しました．

そのため，デザインの仕様が複雑になってもコンポーネント側で対処可能な場合は，木構造の定義・生成方法を変更するだけで済みます．「ButtonGroupItemの定義に変更がない場合は破壊的変更ではない」ともいえるので，コード変更時の影響範囲が分かりやすいというメリットもあります．

2023-03-14 08:23 UTC, ichi-h commented
> dividerの責務って要素を区切りたい、ではなくgroupごとに区切りたいだと思うんで、showDividerのやってることがなんか違う感じするんですが僕だけですかね？

どこで切るかは利用者によりけりな気もするので、自分であればoptionsにkind: "divider"の要素も入れられるようにして、任意の場所に区切り線を出せるような形にすると思います！

2023-03-14 09:24 UTC, RyushiAok commented
> > dividerの責務って要素を区切りたい、ではなくgroupごとに区切りたいだと思うんで、showDividerのやってることがなんか違う感じするんですが僕だけですかね？
> 
> どこで切るかは利用者によりけりな気もするので、自分であればoptionsにkind: "divider"の要素も入れられるようにして、任意の場所に区切り線を出せるような形にすると思います！

確かに今の仕様だと，次のように区切り線を設定できないので，何らかの変更が必要です．
```
ボタン１
ボタン２
-----------
ボタン３
ボタン４
```

kind: "group"に対して

- titleをオプションにする
- インデントするかを選択可能にする
- `groupDivider=true`にする

のような変更を加えることでも対応できますが，確かにkind: "driver"要素を加える方がシンプルで，利用者にとって分かりやすいですね．コンポーネントの制御方法をあまり複雑にすべきでないと思うので，その形で実装してみます．

2023-03-16 02:53 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.vue
> +  },
dividerをitemで突っ込めるようになったので、このpropsはいらなくなったんじゃないかなと思います！

2023-03-16 02:53 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.stories.ts
onClickのactionをstorybookで検知できるようにしたいです！
button系のstoryを参考にしてみてください！
argTypesにonClickというactionを加えるやつです！

2023-03-16 02:53 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.vue
> +  // },
#449 でやると思いますのでこちらのコメントアウトはスルーします！

2023-03-16 05:21 UTC, RyushiAok commented on packages/wiz-ui-next/src/components/base/popup-button-group/popup-button-group.vue
> +  },
groupDividerとbuttonDividerはDividerを自動挿入機能なので，手動で設定できるようになった以上無くても問題ないですが，消しても大丈夫ですか？

2023-03-17 02:21 UTC, ichi-h approved these changes
素晴らしいと思います、ありがとうございました:bow:

2023-03-17 02:23 UTC, merged