Feat/nav item popup list
Wizleap-Inc/wiz-ui pull request #443
Opened 2023-03-09 08:03 UTC by RyushiAok

# タスク

resolve: #356

2023-03-14 05:17 UTC, RyushiAok commented
https://github.com/Wizleap-Inc/wiz-ui/pull/443/commits/9f9dd7cdbcf34454fa38d4abacb4eb622c89cacf WizPopupに変更を加えましたので，ご確認ください．

2023-03-14 10:24 UTC, sor4chi requested changes
popupのshadowがついてる部分を角丸にできますか？

2023-03-21 05:47 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/popup/popup.vue
> +    default: "0px",
この拡張はだいぶゴリ押し感あるよなぁ……
試しにこのborderを消して動作確認してみたところ、問題なく動いてしまったのですが、いかがでしょうか？？

2023-03-26 04:23 UTC, sor4chi reviewed
Popupが開いた状態でのstory差分を撮りたいです。外からMockできますか？

2023-04-05 06:32 UTC, merged