[#442] fix: Search Select のラベルに ellipsis を適用する
Wizleap-Inc/wiz-ui pull request #459
Opened 2023-03-13 13:09 UTC by okakyo

# タスク

resolve: #442

2023-03-14 08:52 UTC, ichi-h approved these changes
ありがとうございます！:pray:

2023-03-14 08:55 UTC, ichi-h requested changes
search-selectorでテスト落ちていたのを見落としておりました……
こちらの解消だけお願いいたします🙇

2023-03-15 13:03 UTC, okakyo commented
[db1c4d8](https://github.com/Wizleap-Inc/wiz-ui/pull/459/commits/db1c4d826723b8a8fe67abff4976c0c45ec04cd6) にて対応しました。

2023-03-17 04:28 UTC, ichi-h approved these changes
改めてありがとうございました！:pray:

2023-03-17 04:29 UTC, merged