Feat/accordion
Wizleap-Inc/wiz-ui pull request #462
Opened 2023-03-14 12:33 UTC by RyushiAok

# タスク

resolve: #450

2023-03-17 12:59 UTC, ichi-h requested changes
ちょっと重そうですがなにとぞよろしくお願いいたします…… 🙇 

- もっと見る・閉じるのところは全体的にcursor: pointerにしたいです！
- 恐らく↑の対応で解決されると思いますが、もっと見る・閉じるの文字が選択できるので、選択できないようにしたいです！
- 折り畳み部分の開閉にフェードイン・フェードアウトが入ることに違和感を感じました……！
  - 開閉の文字は一瞬で切り替わるのに対して、コンテンツがフェードするのは一貫性がないように感じます……！
  - こちらはデザイナーさんから指示はございましたか？？
- アコーディオンをクリックしたときに、アイコンが回転する時と回転しない時があるようです！
  - アイコンの上をクリックすることによってしか回転アニメーションが機能しないようです……

- アコーディオンの中身にpaddingがないのが気になりますね……

![image](https://user-images.githubusercontent.com/85932406/225909077-112dbfd2-a3fd-4efc-b31d-d36f5a71d839.png)

- figmaを見ていた時にちょっと思ったのですが、このコンポーネントはもしかしたら画像のように開閉ボタン自体が下に動くような挙動を想定しているようにも見えたので、これは確認が必要そうです……
  - もしその場合でも、UIライブラリとしては今のような通常のアコーディオンのような挙動も欲しいので、どちらかを選択できるような仕組みが必要になるかもしれません……

![image](https://user-images.githubusercontent.com/85932406/225910500-2b1a55bb-398b-4dc9-a0af-a0774f04e92f.png)

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/accordion.vue
> +
propsの値はtemplate側ではそのまま直で `width` と取れるのでcomputedを宣言する必要はないです！

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/accordion.vue
> +    :class="AccordionDetailsStyle[backgroundColor]"
超細かいところなのですが、変数名とキーが同じオブジェクトを作る場合は、`{ width }` でOKです！

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/accordion.vue
> +
ここジェネリクスに<HTMLDivElement | undefined>が欲しいですね……

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/animation-configuration.ts
> +];
JS/TSの場合、定数はアッパースネークケースで管理するのが一般的ですね！

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/animation-configuration.ts
> +  {
ここのanyはHTMLElementでいけませんか？

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/accordion.vue
> +          <WizIcon
こちらのクリックって何をするイベントになりますか？

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui-next/src/components/base/accordion/animation-configuration.ts
> +];
いや、そもそもなのですが、今回のケースの場合、アニメーションを使わなくても実装できると思います……！
navigationの開閉機能がこちらとほぼ同じ作りになるはずなので、参考にしてみて欲しいと思います……！
（参考のコンポーネントがあることを伝え忘れておりました本当にすみません……）

2023-03-17 12:59 UTC, ichi-h commented on packages/wiz-ui/src/components/base/accordion/accordion.stories.ts
- 最初から開いているパターン
- 色違いパターン

もお願いいたします！

2023-03-18 15:37 UTC, RyushiAok commented on packages/wiz-ui-next/src/components/base/accordion/accordion.vue
> +          <WizIcon
読み込み時に（クリックしていないのにもかかわらず）アイコンが回転しないようにする仕組みです．開閉ボタンではなくアイコンをクリックするときに`canSpin = true`としていたことが，回転しない問題の原因でした．

2023-03-20 02:17 UTC, ichi-h approved these changes
アニメーションをcss animationのやり方に戻して実装しました、一旦これでマージします！

2023-03-20 02:17 UTC, merged