Feat/react icon
Wizleap-Inc/wiz-ui pull request #550
Opened 2023-04-05 07:19 UTC by RyushiAok

# タスク

resolve: #549

2023-04-06 06:51 UTC, sor4chi requested changes
classnameが複数あるケースでメンテナンス性が損なわれてしまうので
https://github.com/lukeed/clsx
を使ってみてください

2023-04-10 14:11 UTC, ichi-h reviewed
ビルドコマンド走らせたときにエラー出るのですが、こちらって例の #564 で解決するものでしょうか？

```
@wizleap-inc/wiz-ui-icons:build: > @wizleap-inc/wiz-ui-icons@0.0.0 lint:react /home/ichi/dev/wizleap/wiz-ui/packages/icons
@wizleap-inc/wiz-ui-icons:build: > eslint --fix ../wiz-ui-react/src/components/icons/*.{ts,tsx,vue}
@wizleap-inc/wiz-ui-icons:build: 
@wizleap-inc/wiz-ui-icons:build: 
@wizleap-inc/wiz-ui-icons:build: Oops! Something went wrong! :(
@wizleap-inc/wiz-ui-icons:build: 
@wizleap-inc/wiz-ui-icons:build: ESLint: 8.37.0
@wizleap-inc/wiz-ui-icons:build: 
@wizleap-inc/wiz-ui-icons:build: No files matching the pattern "../wiz-ui-react/src/components/icons/*.vue" were found.
@wizleap-inc/wiz-ui-icons:build: Please check for typing mistakes in the pattern.
@wizleap-inc/wiz-ui-icons:build: 
@wizleap-inc/wiz-ui-icons:build:  ELIFECYCLE  Command failed with exit code 2.
@wizleap-inc/wiz-ui-icons:build: ERROR: "lint:react" exited with 1.
@wizleap-inc/wiz-ui-icons:build:  ELIFECYCLE  Command failed with exit code 1.
@wizleap-inc/wiz-ui-icons:build: ERROR: command finished with error: command (/home/ichi/dev/wizleap/wiz-ui/packages/icons) pnpm run build exited (1)
command (/home/ichi/dev/wizleap/wiz-ui/packages/icons) pnpm run build exited (1)
```

2023-04-10 14:11 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/buttons/icon/stories/icon.stories.tsx
> +    const icons = () =>
github actionsによると、 `'args' is defined but never used` とのことなので消しても大丈夫そうです！

2023-04-10 15:57 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/buttons/icon/stories/icon.stories.tsx
> +    const icons = () =>
> ビルドコマンド走らせたときにエラー出るのですが、こちらって例の https://github.com/Wizleap-Inc/wiz-ui/pull/564 で解決するものでしょうか？

`package/icons`配下で`pnpm build`を叩く場合は問題はないのですが、root配下で`pnpm build`を叩いた時、指定したパターンに一致するファイルがないとエラーになるようでしたので、余計な拡張子パターンを削除いたしました:pray:

> github actionsによると、 'args' is defined but never used とのことなので消しても大丈夫そうです！

消しました！

2023-04-11 02:25 UTC, ichi-h approved these changes
あざます！

2023-04-11 02:33 UTC, merged