Feat/react text area
Wizleap-Inc/wiz-ui pull request #558
Opened 2023-04-05 15:54 UTC by RyushiAok

# タスク

resolve: #557

2023-04-12 09:43 UTC, sor4chi requested changes
修正お願いします

2023-04-12 09:43 UTC, sor4chi commented on packages/wiz-ui-react/src/components/base/textarea/components/text-area.tsx
> +const _TextArea = ({
入力系はreact-hook-formなどを使うことを想定してとりあえずforward refしましょう

2023-04-12 09:43 UTC, sor4chi commented on .changeset/lucky-laws-exercise.md
> +clsx をメンテナンス性を担保するために導入
nice

2023-04-17 05:01 UTC, sor4chi requested changes
お願いします

2023-04-17 05:01 UTC, sor4chi commented on packages/wiz-ui-react/src/components/base/textarea/components/text-area.tsx
> +};
type Props = {
...
} & ComponentProps<'textarea'>
の方がいい気がします

2023-04-17 05:28 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/textarea/components/text-area.tsx
> +};
変更しました！

2023-04-19 09:21 UTC, ichi-h approved these changes
LGTM🦍

2023-04-19 09:28 UTC, merged