Feat/react box
Wizleap-Inc/wiz-ui pull request #573
Opened 2023-04-08 07:08 UTC by RyushiAok

# タスク

resolve: #572

2023-04-12 10:13 UTC, sor4chi requested changes
修正お願いします

2023-04-12 10:13 UTC, sor4chi commented on .changeset/happy-dancers-argue.md
> +WizBox の React 対応
これもいらんすね

2023-04-12 15:37 UTC, RyushiAok commented on .changeset/happy-dancers-argue.md
> +WizBox の React 対応
けしました

2023-05-09 07:22 UTC, wmoai reviewed
コメントしました！

あと気になったのは、BoxコンポーネントのStoryもあったほうが良いかもと思いました。（Vue版の方も無いのでなにか理由があるかもしれませんが）

2023-05-09 07:22 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      overflow: snapScroll ? "scroll" : overflow,
OSの設定でスクロールバーを常に表示するようにしていると、`overflow: scroll` を指定したときスクロールが無い方向のスクロールバーも表示されてしまうというのがあるので、特に理由がなければ `overflow: auto` にしていたほうが良い場合が多いというのがあります。

例）`overflow: scroll`だとx軸方向のスクロールがなくてもスクロールバーは表示される
![image](https://user-images.githubusercontent.com/270422/237022551-21d21594-d371-496d-ae9f-3ab03727c1d9.png)

2023-05-09 07:22 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      overflowY,
実装上`snapScroll`を設定していて`overflowX`および`overflowY`を指定していなければ`overflow`には`scroll`が入るはずですが、実際には入らないようです。

理由としては、JSXのstyleに
```ts
{
  overflow: "scroll",
  overflowX: undefined,
  overflowY: undefined,
}
```
を与えたときに、reactが`overflowX`と`overflowY`の指定を`overflow`にマージして`overflow: undefined undefined`と解釈してしまうことで`overflow`が指定なしになってしまうようです。

2023-05-09 21:15 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      scrollSnapType: snapScroll && snapScroll,
51bbb0c こちらにて修正いたしました……！

2023-05-09 21:16 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      zIndex: zIndex && +getZIndexCss(zIndex),
1b1ea7b こちらにて修正いたしました！
`wiz-ui-next`でも同様のリファクタが必要かもしれません。

2023-05-09 21:17 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      overflowY,
94c79cd こちらにて修正いたしました！

2023-05-11 01:54 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/box/components/box.tsx
> +      zIndex: zIndex && +getZIndexCss(zIndex),
FIYですがVue側の`style.zIndex`は`string`を許容しないため`number`にキャストしているようです！

2023-05-12 02:30 UTC, wmoai reviewed
@RyushiAok 以下のように修正入れてみたので、確認お願いします！

* `overflow` スタイル算出における props 指定の優先度調整 [9fe2fb6](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/9fe2fb67bf14056cb5b206ace2ef0ca31fe2b0a5)
* `bgColor` に `gradient` を指定しても効かない問題の修正 [b3d1be1](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/b3d1be11c676a572dc1eb9bc94d8570b398823b6)
* `React.memo()` を外す [a7013ed](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/a7013ed675c5bbb9bc055214f79e8819716aa73c)
* Story の見栄えを調整 [c225a63](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/c225a637d6fb7d54d8b457eb0773b0d36dc4fe2d)

2023-05-12 04:07 UTC, wmoai commented
あと、コンポーネントの変数名にアンダースコアを付けている意味はあまりない気がしたので削除してみたのですが、まずいでしょうか？ [fcf703b](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/fcf703baa8ca72133f8bd4e5f52303da25ccaa65)

スコープの異なる同名の変数を区別するために頭にアンダースコアを付けることはあると思いますが、今回の場合はコンポーネントを `WizBox` と命名して export していることは記述から明らかなので、export していないコンポーネントにアンダースコアを付ける意味はあまり無いように思いました。

2023-05-12 14:44 UTC, RyushiAok commented
@wmoai 確認いたしました！ありがとうございます🙏

・`snapScroll` Propsについて、`overflow` 決定優先度に関するドキュメントコメントを追加しました！ [1bdf02e](https://github.com/Wizleap-Inc/wiz-ui/pull/573/commits/1bdf02ea31498c312fa5a540f87757c8f30122d2)

2023-05-15 01:03 UTC, wmoai approved these changes
LGTM !

2023-05-16 01:16 UTC, merged