feat(base-input): PrivateBaseInputのReact対応
Wizleap-Inc/wiz-ui pull request #578
Opened 2023-04-08 14:06 UTC by RyushiAok

# タスク

resolve: #577

2023-04-12 09:45 UTC, sor4chi requested changes

2023-04-12 09:45 UTC, sor4chi commented on packages/wiz-ui-react/src/components/base/inputs/base/components/base.tsx
> +const _PrivateBaseInput = ({
forwardRefはってください

2023-04-12 15:23 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/inputs/base/components/base.tsx
> +const _PrivateBaseInput = ({
はりました！

2023-04-19 01:37 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/inputs/base/components/base.tsx
> +    }, [hasFocus, error]);
このuseMemoって必要ですか？
この処理が重たいものではないのでメモ化するほどのものではないというのと、React.memoで括られたコンポーネントで使われる可能性は恐らくないので、別にいらないんじゃないか、という考えです

2023-04-19 03:56 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/inputs/base/components/base.tsx
> +    }, [hasFocus, error]);
削除しました！

2023-04-19 09:14 UTC, ichi-h approved these changes
LGTM🦍

2023-04-19 09:15 UTC, merged