Fix/snackbar lifecycle
Wizleap-Inc/wiz-ui pull request #608
Opened 2023-04-11 10:07 UTC by RyushiAok

# タスク

resolve: #566

2023-04-12 10:10 UTC, sor4chi requested changes
修正お願いします。

2023-04-12 10:10 UTC, sor4chi commented on .changeset/healthy-numbers-hang.md
> +Snackbar のライフサイクルのバグを修正
もうちょっと具体的に書けますか...

2023-04-12 10:10 UTC, sor4chi commented on packages/wiz-ui-next/src/hooks/use-global-provider.ts
> +const useMenu = () => {
こちらuse-memo.tsとuse-snackbar.tsの蓋ファイルに切り出してglobal providerをprovideのみにできますか？

2023-05-16 01:56 UTC, ichi-h approved these changes
どうもです！:pray:

2023-05-16 01:56 UTC, merged