Feat/react popup
Wizleap-Inc/wiz-ui pull request #613
Opened 2023-04-11 18:16 UTC by RyushiAok

# タスク

resolve: #612

2023-04-21 01:10 UTC, ichi-h reviewed
とりあえずパッと見える範囲でレビューしました！

2023-04-21 01:10 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/popup/components/popup-trigger.tsx
> +};
このコンポーネントのcloseの時と理由は同様ですね……

2023-04-21 01:10 UTC, ichi-h commented on packages/wiz-ui-react/src/hooks/use-click-outside.ts
> +
ここでcallbackをuseRefでラップしている理由ってございますか？？

2023-04-21 01:10 UTC, ichi-h commented on packages/wiz-ui-react/src/hooks/use-global-provider.ts
> +    );
vueになっています……笑

2023-04-21 01:10 UTC, ichi-h commented on packages/wiz-ui-react/src/hooks/use-global-provider.ts
> +};
これはまだ途中ですかね？

2023-04-21 01:10 UTC, ichi-h commented on packages/wiz-ui-react/src/hooks/use-portal.ts
こちらって使われておりますか？？

2023-04-22 11:43 UTC, RyushiAok commented on packages/wiz-ui-react/src/hooks/use-global-provider.ts
> +    );
53a5157 お恥ずかしい、、、修正いたしました！

2023-04-22 11:45 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
> +  };
e4cd071 WizPopupContentで再レンダリングの制御するように修正いたしました！

2023-04-22 11:46 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup-content.tsx
> +    const x = trigger.x - content.width + window.scrollX < 0 ? "r" : "l";
e116af1 修正しました！

2023-04-22 11:49 UTC, RyushiAok commented on packages/wiz-ui-react/src/hooks/use-portal.ts
71926ef 消しました！

2023-04-22 12:34 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
> +  const contextValue = {
797b1b8 修正しました！

2023-04-25 06:38 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup-close.tsx
> +};
9b5f505 こちらでWizPopupCloseButtonを修正いたしました。

一連のコンポーネントは、ChakraのPopoverを意識して実装したものです。確かにそのような方法でも実現可能ですし、そもそもvue版では開閉専用のコンポーネントは存在しないので、WizPopupTrigger・WizPopupCloseButtonは不要かもしれません……。あれば便利かと思い実装したのですが、問題があれば修正します！

2023-04-25 06:39 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup-trigger.tsx
> +};
dbc6e36 修正しました

2023-04-26 13:38 UTC, sor4chi commented
wiz-ui-reactのbundle checkerが異様にバンドルサイズ増えてるんですが何かまずいものバンドルしてないですか？

2023-04-26 13:55 UTC, sor4chi requested changes

2023-04-26 13:55 UTC, sor4chi commented on packages/wiz-ui-react/package-lock.json
消してpnpm iでlock更新してください

2023-05-02 09:29 UTC, ichi-h reviewed
細かい挙動は今後のPRで改修していくとして、方針だけ練らせていただければと思います…… 🙇

2023-05-02 09:29 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/popup/components/popup-trigger.tsx
この方向の場合、いくつかの懸念があって、

- Trigger『内』のコンポーネントのonClickをどう扱うか
  - 仮に書いてあった場合は上書き、そうでなかった場合はonClick属性が空のbutton的なコンポーネントが存在することになりそう
  - 考えたいことは、この2つの挙動および状態が自然かどうかというお話ですね
    - 書いてあった場合
      - trigger自体にonClickのpropsを受け取れるようにしているので、追加でクリック時の挙動を実装した場合はこれを使ってねという意図だと思うのですが、それでOKとするか
    - 書いてなかった場合
      - こっちが厄介で、仮にonClick属性の登録を必須とするようなコンポーネントが内部に入ってきた場合、この仕様だと実装不可能になると思うんですよね
      - 何もしない空の関数を入れればよいんですが、それはそれでかなり不自然だと思いますし……
      - 仮に上記の問題がなかったとして、trigger側からonClickを付与するといっても、onClick属性が空のbutton的なコンポーネントがあることが自然か問われると、そうではなさそうと感じてしまいます……

思ったことは、cloneElementでrefとclickを両方セットにする必要があるか、というところですね
つまり、popupの利用者視点で見てみると、trigger内のonClickはpopupの開閉動作含め自由に設定できるはずなので、それをcloneElementの時点で付与する必要があるか、というお話です

ごちゃごちゃお話しましたが、結論としては、cloneElementで貼り付けるのはrefだけで、onClickの実装は利用者に任せる、のほうが小回りが利きやすい & わかりやすいんじゃないかなと思ったのですが、どうだろう……？

2023-05-02 09:29 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/popup/components/popup-close.tsx
このコンポーネントってwiz-uiから提供する必要ありそうかな……？
素のbuttonがreturnされているっていうのもそうなんだけど、このコンポーネントってpopupの利用者側が必要な場合に実装すればよいのでは……？　と思いまして…… 💦

2023-05-02 09:29 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/popup/components/popup-trigger.tsx
いや、trigger内に突っ込まれたコンポーネントがrefを持っていたとしても同様のことが言えるんじゃないかな……？

2023-05-02 09:29 UTC, ichi-h commented on packages/wiz-ui-react/src/components/base/popup/components/popup-trigger.tsx
普通にdivでwrapしたところにref貼ってonClickは利用者に実装してもらうが一番丸そうに感じてきました……笑

2023-05-07 09:20 UTC, RyushiAok commented
なるほど、、

そもそもの問題ですが、PopupTriggerにonClickが用意されている現時点の実装は微妙ですね……。
TriggerをUIフレームワーク側で用意する場合は、子要素のpropsにPopupの開閉ロジックをマージしてcloneElementするのが一般的な実装方法のようです。

あと参考になるかとも思い、色々なUIフレームワークのPopup実装について調査いたしました……！

## Trigger制御タイプ

**React Bootstrap**
  - https://react-bootstrap.github.io/components/overlays/#popovers
  - OverlayTriggerコンポーネントの引数にPopupするコンポーネントを指定します。

**Semantic UI**
  - https://react.semantic-ui.com/modules/popup/#types-popup
  - Popupの引数にPopupコンテンツ・Tiggerの両方を指定します。

**Ant Design**
  - https://ant.design/components/popover
  - Triggerの引数にPopupコンテンツを指定します。

**Chakra UI**
  - https://chakra-ui.com/docs/components/popover/usage
  - これを参考に実装しました。

**NextUI**
  - https://nextui.org/docs/components/popover#popover
  - Chakura UI同様のインターフェースです。

**Radix UI**
  - https://www.radix-ui.com/docs/primitives/components/popover
  - Chakura UIと同様です。

## ref制御タイプ
**MUI**
  - https://mui.com/material-ui/react-popover/#basic-popover
  - Popoverコンポーネントの引数に、anchorEl（popup表示位置を指定するref）を指定します。


## 提案

**Triggerがある場合**
- 開閉ロジックを利用者が意識しなくてよい 
  - Popupコンポーネントが配置される数に、Ref管理の負担が比例しない
- 有名どころのUIフレームワークにはTriggerタイプよく採用されているので、親しみやすい（？）
- Triggerコンポーネントの子要素の挙動が、利用者にとって不明瞭（ご指摘の点）

**Ref制御する場合**
- 自由にアンカーを設定できる（Triggerの位置に縛られない）
- 実装が軽い
- PopupのRef管理ロジックを利用者自身で実装する必要がある
  - 大量配置する場合などは、Triggerコンポーネントを利用者側で実装すればRef管理を隠蔽可能です。

なので、WizUIではPopupを

1. MUI的なRef制御を要求するコンポーネントをベースとして実装し、
2. Ref管理を隠蔽するコンポーネント(Trigger, Close)もついでに提供する（不要かもしれません）

という形にすれば便利かもしれません……！

2023-05-11 05:22 UTC, RyushiAok commented
refパターンでいきます！

2023-05-13 17:24 UTC, RyushiAok commented
[8f54a30](https://github.com/Wizleap-Inc/wiz-ui/pull/613/commits/8f54a3034b56260965b86cbaf3b9419c041b3251)

座標計算の都合上、

- 表示位置の基準が変わると困る
- 親のスタイルが適用されてほしくない

という理由で、portalを使わない場合を考えると、このような配置を強制する仕組みが要るかもしれません。

```html
<div>
  <anchor/>
  <popup/>
</div>
```

2023-05-16 01:09 UTC, wmoai reviewed
気になったところをコメントしました！

2023-05-17 08:43 UTC, RyushiAok commented
以下、レビュー箇所の修正です。

e12daf7 `onClose`にProps名を変更しました
3e3be8c placementまわりのリファクタです
8fd2059 835f04c portalのリファクタです
cfd4b66 不要なProvider関連のファイルを削除しました
fad1ae9 useClickOutsideのリファクタです
76d0e16 開閉ロジック（アニメーション込み）をhookに切り出しました。

2023-05-18 03:46 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/popup/hooks/use-popup-animation.ts
> +const toggleWithFadeAnimation = {
この関数群の主な責務はフェードアニメーションだと考えていて、トグルするかどうかは使う側がコールバックに何を書くか次第なので、`toggleWithFadeAnimation` という命名に少し違和感を持ちました。

2023-05-18 03:46 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/popup/hooks/use-popup-animation.ts
> +    onStart();
これらの関数が private になったことにより、一層 `onStart` をコールバックとして受け取る意味がなくなったように感じました。
`onStart` の処理は関数呼び出し直後に同期的に実行されるので、呼び出し側で `open()` の直前にその処理を書けばよく、コールバックとして定義する意味が無いように思いました。

また、そう考えていくとそもそも `toggleWithFadeAnimation` が `usePopupAnimation` から切り出されている意味ってあるのか？と思ったりしました。

2023-05-18 03:46 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/popup/hooks/use-popup-animation.ts
> +  close: (target: HTMLDivElement, onClose: () => void) => {
[IMO] `close` が引数として `onClose` を持っていると、それがいつ発火するのか分かりにくいと思いました。
今回の場合、コールバックが発火するのは「アニメーション終了後」なので `onFinish` や `onComplete` といった命名のほうが良いと思います。

2023-05-18 03:46 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/portal/components/portal.tsx
> +    if (!mount || !elNode) return;
`mount` は型的に null チェックする必要は無いように思いましたが、何か意図があるんでしょうか？

[nits] 細かいですが、`mount` だと動詞感があって関数のように見えてしまうので、例えば `protalContainer` みたいな命名のほうが良いと思います。

2023-05-18 03:46 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
> +        isPortal: true,
[IMO] 現状の判断としてはポータルを使用するのがデフォルトのはずですが、このインターフェースでは `isPortal: true` を指定しないとポータルではなくなってしまうので「ポータルじゃないのがデフォルトでポータル仕様がオプション」の意味付けになっている気がします。
ポータルがデフォルトであることを示すために `isNotPortal: boolean` のようなインターフェースにするのが良いのではと思いました。。

2023-05-18 09:45 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/components/popup.tsx
> +        isPortal: true,
`asDecendantElement : boolean` 
default: false

2023-05-23 08:27 UTC, wmoai reviewed
気づいたことをコメントしたのですが、時間も差し迫ってきているので対応優先度を付けました。

**【優先度：低】** が付いているコメントについてはこの PR で対応せず、別の Issue を立ててそちらで対応しましょう。

それ以外の指摘は、挙動が怪しかったり、簡単に対応できるものなので、ご確認ください。

2023-05-23 18:04 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/stories/wrap/template.tsx
> +export const PopupWrapTemplate = (args: any) => {
この書き方初めて知りました。ありがとうございます！

2023-05-23 18:06 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/test/boundary.test.ts
> +    bound: { x: 0, y: 0, width: 100, height: 100 } as DOMRect,
何故か落ちるんですよね……
```
 FAIL  src/components/base/popup/test/boundary.test.ts [ src/components/base/popup/test/boundary.test.ts ]
ReferenceError: DOMRect is not defined
 ❯ src/components/base/popup/test/boundary.test.ts:7:16
      5| describe("isOutOfBound", () => {
      6|   const input: Args = {
      7|     bound: new DOMRect(0, 0, 100, 100), // { x: 0, y: 0, width: 100, height: 100 } as DOMRect,
       |                ^
      8|     content: { x: 10, y: 10, width: 20, height: 20 } as DOMRect,
      9|     anchor: { x: 50, y: 50, width: 30, height: 30 } as DOMRect,
```

2023-05-23 18:26 UTC, RyushiAok commented on packages/wiz-ui-react/src/components/base/popup/utils/wrap.ts
> +export const reflection = {
回り込みロジックが、はみ出た方向に対する線対称移動（反射）の組み合わせによって実現されるためです。

2023-05-23 19:56 UTC, RyushiAok commented
## gapを考慮した回り込みロジックの確認

https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/31d180ae-a282-4ba8-afe4-a8bfc4f20ecf

https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/680baa39-bda9-48a2-9045-2e4aa45bd9c2

https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/5fa4ffef-2c57-4bfc-8329-17d63a179c39

https://github.com/Wizleap-Inc/wiz-ui/assets/55625375/508130b7-17eb-4977-b76f-745fa6c449d2

## 考慮事項

アンカーと境界との間にPopupが収まる十分な隙間がある場合、そこに収まるようにGapを小さくする方が自然かもしれません。

2023-05-25 04:44 UTC, wmoai commented on packages/wiz-ui-react/src/components/base/popup/utils/wrap.ts
> +    bound.height < anchor.y + anchor.height + content.height + window.scrollY,
ここは右辺に `anchor.height` を加算する必要は無いように思いました。

2023-05-26 01:11 UTC, wmoai approved these changes
LGTM !

2023-06-08 02:21 UTC, merged