fontSizeを大きくした際にiconのサイズが変わらないバグの修正
Wizleap-Inc/wiz-ui pull request #713
Opened 2023-05-11 13:21 UTC by okakyo

# タスク

resolve: #695

2023-05-31 07:13 UTC, sor4chi requested changes
一点だけお願いいたします！

2023-05-31 07:13 UTC, sor4chi commented on .changeset/smooth-flies-perform.md
> +"@wizleap-inc/wiz-ui": patch
使用者側にレイアウトシフトが発生するPRなので一応`Breaking Changes`ということで`minor`リリースに変えていただきたいです！

2023-06-01 16:05 UTC, okakyo commented on .changeset/smooth-flies-perform.md
> +"@wizleap-inc/wiz-ui": patch
[360819d](https://github.com/Wizleap-Inc/wiz-ui/pull/713/commits/360819d5982b29f19af5e1bd52ccc5df41fdc8a3)　にて対応しました。

2023-07-27 10:01 UTC, ichi-h approved these changes
react対応しました！
ありがとうございました！

2023-07-27 10:01 UTC, merged