[#660] Tooltip の VRT でエラーが発生しているバグの修正
Wizleap-Inc/wiz-ui pull request #715
Opened 2023-05-11 14:25 UTC by okakyo

# タスク

resolve: #660

2023-05-31 08:32 UTC, sor4chi requested changes
お願いいたします。

2023-05-31 08:32 UTC, sor4chi commented on .changeset/smart-avocados-stare.md
> +fix tooltip vrt bug
Changesetは使用者側の変更確認でおもに利用されるものです。
DX側の修正や変更は実際にwiz-uiバンドルに含まれないため使用者側視点では何も変わってないことになってしまいます。

そのため、今回は`vrtのバグを直した`よりも`tooltipにanimationさせないようにするpropsを追加した`というコンテキストの方が良いと思います。

2023-05-31 08:32 UTC, sor4chi commented on .changeset/smart-avocados-stare.md
> +"@wizleap-inc/wiz-ui": patch
機能追加をしているので`patch`ではなく`minor`でお願いいたします。

2023-05-31 08:32 UTC, sor4chi requested changes
お願いいたします。

2023-06-15 09:44 UTC, ichi-h commented
ごめんなさいこちらで解決したのでcloseします 🙇  🙇  🙇  🙇  🙇  🙇  🙇  🙇 
#841

2023-06-15 09:44 UTC, closed without merging